# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180421_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_acitve',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
